service: bref-test-tmp

provider:
  name: aws
  region: eu-central-1
  runtime: provided

plugins:
  - ./vendor/bref/bref

functions:
  website:
    handler: index.php
    layers:
      - ${bref:layer.php-74-fpm}
    events:
      - http:
          path: "/"
          method: ANY
